### ISSUE TITLE
React project installation

### ISSUE THREAD

**Issue by MMikhailova** [Job-Advisor-project/FrontEnd#25]
- [x] create a react project in the Frontend repo
- [x] figure out how to use React and Bootstrap libraries (installation, import components)
- [x] create a list of components needed for the homepage
- [x] create a new branch and try to import a component from React

**Comment by minjupgeorge** [comment]
List of components needed for homepage
https://mui.com/material-ui/getting-started/overview/

1) Header and logo //https://betterprogramming.pub/building-a-basic-header-with-materialui-and-react-js-d650f75b4b0a
2)Navbar//https://javascript.works-hub.com/learn/how-to-create-a-responsive-navbar-using-material-ui-and-react-router-f9a01
3)Search bar //https://www.npmjs.com/package/material-ui-search-bar
4)Button //https://mui.com/material-ui/react-button/
5)Carousel slide//https://www.npmjs.com/package/react-material-ui-carousel
6)Contact form//https://dev.to/hibaeldursi/creating-a-contact-form-with-validation-with-react-and-material-ui-1am0
7)Footer //https://morioh.com/p/795818fd3239

**Comment by minjupgeorge** [comment]
figure out how to use React and Bootstrap libraries (installation, import components)

I prefer material-ui and tailwind css... still I need 8hrs more to check the feasibility
To run react project need to update yml file

ls:
.js: kebab - case
.jsx kebab-case

**Comment by minjupgeorge** [comment]
create a new branch and try to import a component from React
Trying to import header component
