### ISSUE TITLE
Create Header Navigation bar for jobadvisor homepage

### ISSUE THREAD

**Issue by minjupgeorge** [Job-Advisor-project/FrontEnd#47]
- [x] Create a branch header-navigation
- [x] Create header component from material-ui 
- [x] Use Drawer component to make it responsive
- [x] install necessary npm commands when required example ` install @mui/icons-material `
- [x] run pull request

**Comment by ayobamiseun** [comment]
I @minjupgeorge I will like to jump on this if you don't mind.
