### ISSUE TITLE
Create Search Bar Component

### ISSUE THREAD

**Issue by FennyWilriani** [Job-Advisor-project/FrontEnd#74]
- [x] Create input bar, button, and search icon. @MMikhailova 
- [x] Create a functional component for the Search bar. @MMikhailova 
- [ ] Create a function to filter data. @FennyWilriani 
- [ ] Display the result on the page. @minjupgeorge

**Comment by MMikhailova** [comment]
@FennyWilriani Thank you for creating the issue for all of us. I already created an issue for my part so you can leave only your part here.:)
