### ISSUE TITLE
Fix : Fix the design of carousel slides

### ISSUE THREAD

**Issue by minjupgeorge** [Job-Advisor-project/FrontEnd#75]
- [ ] To display minimum 3 cards of carousel slides on home page
- [ ] Create a branch
- [ ] Merge pull request

**Comment by MMikhailova** [comment]
@minjupgeorge We also need to style the carousel so it looks as per design. Images, spacing between cards and arrows not overlap with cards. Please let us know if you can style the carousel or you want to assign it to somebody else.
